// Chrome Api Keys
export const ACTIVE_USERNAME_KEY = "activeUsername";
export const ALL_USERNAMES_KEY = "allUsernames";



// MISC KEYS
export const PING_REQUEST = "PING_REQUEST";
export const PONG_RESPONSE = "PONG_RESPONSE";
export const REQUEST_START_SCRAPE_FOLLOWINGS = "REQUEST_START_SCRAPE_FOLLOWINGS";
export const RESPONSE_START_SCRAPE_FOLLOWINGS = "RESPONSE_START_SCRAPE_FOLLOWINGS";
export const REQUEST_STOP_SCRAPE_FOLLOWINGS = "RESPONSE_FAILED_STOP_SCRAPE_FOLLOWINGS";
export const REQUEST_LIKE_AND_RT = 'REQUEST_LIKE_AND_RT';
export const RESPONSE_LIKE_AND_RT = 'RESPONSE_LIKE_AND_RT';
export const REQUEST_SCROLL_LIKE_AND_RT_TARGET = 'REQUEST_SCROLL_LIKE_AND_RT_TARGET';
export const RESPONSE_SCROLL_LIKE_AND_RT_TARGET = 'RESPONSE_SCROLL_LIKE_AND_RT_TARGET';
export const REQUEST_REPLY_WITH_URL = "REQUEST_REPLY_WITH_URL";
export const RESPONSE_REPLY_WITH_URL = "RESPONSE_REPLY_WITH_URL";
export const REQUEST_RADIO_WATER_MELON_SCREENSHOT = "REQUEST_RADIO_WATER_MELON_SCREENSHOT";
export const RESPONSE_RADIO_WATER_MELON_SCREENSHOT = "RESPONSE_RADIO_WATER_MELON_SCREENSHOT";
export const ON_CLIPBOARD_COPY = "ON_CLIPBOARD_COPY";
export const REQUEST_KEEP_BACKGROUND_ALIVE = "REQUEST_KEEP_BACKGROUND_ALIVE";
export const RESPONSE_KEEP_BACKGROUND_ALIVE = "RESPONSE_KEEP_BACKGROUND_ALIVE";
